# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

monte_carlo <- function(S0 = 140, k = 150, volatility = 0.24, interest_rate = 0.07, time_to_maturity = 0.75, barrier_level = 120, nReps = 10000L) {
    .Call(`_myMC2_monte_carlo`, S0, k, volatility, interest_rate, time_to_maturity, barrier_level, nReps)
}

rcpp_hello <- function() {
    .Call(`_myMC2_rcpp_hello`)
}

rcpp_hello_world <- function() {
    .Call(`_myMC2_rcpp_hello_world`)
}

